package com.balvin.myid;

public class Constants {

    public static final String ACTIVATION="WWYFMGRGUYWYFUZYWGTYUWCFSTCFYTGFWTNWPYFTZTPGNTAFWGRGVFTGNFTASNAGMNGNAYTAUUYYQYWNFTCTPAQGSGGTVNUTUTGFGAGYQTFFTNRF";

}
